version: '3.8'

services:  
 dotnetcore:
  build: 
   context: .
   dockerfile: api-server.dockerfile
  container_name: api_server
  ports:
   - "5000:5000"
  networks:
   - app-network

 postgres: 
  image: postgres
  container_name: postgres
  ports:
   - "5432:5432"
  environment:
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=password
   - POSTGRES_DB=postgres
  networks:
   - app-network

networks:
 app-network:
  driver:  bridge